export DO_NOT_TRACK=1                             # https://consoledonottrack.com
export ALGOLIA_CLI_TELEMETRY=0                    # Algolia CLI
export AMPLIFY_DISABLE_TELEMETRY=1                # AWS Amplify
export APOLLO_TELEMETRY_DISABLED=true             # Apollo Router/Rover CLI
export ASTRO_TELEMETRY_DISABLED=1                 # Astro CLI
export CALCOM_TELEMETRY_DISABLED=1                # Cal.com
export CHECKPOINT_DISABLE=1                       # Prisma, HashiCorp (Terraform, Packer)
export CLOUDSDK_CORE_DISABLE_USAGE_REPORTING=true # Google Cloud SDK
export DA_TEST_DISABLE_TELEMETRY=1                # JavaScript Debugger (vscode-js-debug)
export DATAHUB_TELEMETRY_ENABLED=false            # DataHub CLI
export DDB_LOCAL_TELEMETRY=0                      # DynamoDB local
export DISABLE_ZAPIER_ANALYTICS=1                 # Zapier Platform CLI
export DOTNET_CLI_TELEMETRY_OPTOUT=1              # .NET CLI
export DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT=1  # .NET Interactive
export EXPO_NO_TELEMETRY=1                        # Expo CLI
export GATSBY_TELEMETRY_DISABLED=1                # Gatsby
export GOTELEMETRY=off                            # Go
export HASURA_GRAPHQL_ENABLE_TELEMETRY=false      # Hasura GraphQL Server/Console/CLI
export MSSQL_TELEMETRY_ENABLED=FALSE              # Azure SQL Edge
export NEXT_TELEMETRY_DISABLED=1                  # Next.js
export NG_CLI_ANALYTICS=false                     # Angular CLI
export NUXT_TELEMETRY_DISABLED=1                  # Nuxt
export SAM_CLI_TELEMETRY=0                        # AWS SAM CLI
export SFDX_DISABLE_TELEMETRY=true                # Salesforce CLI
export SST_TELEMETRY_DISABLED=1                   # SST
export STORYBOOK_DISABLE_TELEMETRY=1              # Storybook
export STRIPE_CLI_TELEMETRY_OPTOUT=1              # Stripe CLI
export YARN_ENABLE_TELEMETRY=0                    # Yarn
