#!/bin/zsh

# Changes to the specified directory and lists its contents (cd + ls)
cdls() {
	local dir="${1:=${HOME}}"

  if [[ -d "$dir" ]]; then
		builtin cd "$dir" && ls "${@:2}"
	else
		echo "cdls: no such directory: ${dir}"
	fi
}
