#!/usr/bin/env zsh

# Changes to the specified directory and lists its contents (cd + ls)
function cdls() {
  local dir="${1:=${HOME}}"

  if [[ -d "${dir}" ]]; then
    builtin cd "${dir}" && ls "${@:2}"
  else
    echo "$0: no such directory: ${dir}"
  fi
}
