#!/usr/bin/env zsh

# Kills the process(es) running on the specified port(s). Ports can be specified
# as either a single port number or a range of ports separated by a minus sign.
function killport() {
  if (($# == 0)); then
    echo "usage: $0 port ..."
    return 1
  fi

  local port
  local pids
  for port in "$@"; do
    pids="$(lsof -i :${port} -t)"

    if [[ -n "${pids}" ]]; then
      echo "$0: killing process(es) ${(f)pids} on port(s) ${port}..."
      xargs kill -s KILL <<< "${pids}"
    else
      echo "$0: no process found on port ${port}"
    fi
  done
}
