" 1 important
set nocompatible          " (don't) behave very Vi compatible

" 2 moving around, searching and patterns
set incsearch             " show match for partly typed search command
set ignorecase            " ignore case when using a search pattern
set smartcase             " override 'ignorecase' when pattern has uppercase characters

" 4 displaying text
set smoothscroll          " scroll by screen line
set nowrap                " long lines (don't) wrap
set number                " show the line number for each line

" 5 syntax, highlighting and spelling
filetype plugin indent on " type of file; triggers the FileType event when set
syntax enable             " enable syntax highlighting
set nohlsearch            " (don't) highlight all matches for the last used search pattern

" 8 terminal
set term=xterm-256color   " name of the used terminal

" 11 messages and info
set ruler                 " show cursor position below each window

" 14 tabs and indenting
set tabstop=2             " number of spaces a <Tab> in the text stands for
set shiftwidth=2          " number of spaces used for each step of (auto)indent
set softtabstop=2         " if non-zero, number of spaces to insert for a <Tab>
set shiftround            " round to 'shiftwidth' for '<<' and '>>'
set expandtab             " expand <Tab> to spaces in Insert mode
set autoindent            " automatically set the indent of a new line

" 24 multi-byte characters
set encoding=utf8         " character encoding used in Vim
